CREATE TABLE company_user
(
    id    int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    login varchar(255) NOT NULL,
    CONSTRAINT company_user_pkey PRIMARY KEY (id),
    CONSTRAINT company_user_uniq_login UNIQUE (login)
);

-- Пациенты в Новой системе:
CREATE TABLE patient_profile
(
    id              int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name      varchar(255) NULL,
    last_name       varchar(255) NULL,
    old_client_guid varchar(255) NULL,
    status_id       int2         NOT NULL,

    CONSTRAINT patient_profile_pkey PRIMARY KEY (id)

);

-- Заметки
CREATE TABLE patient_note
(
    id                       int8          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_date_time        timestamp     NOT NULL,
    last_modified_date_time  timestamp     NOT NULL,
    created_by_user_id       int8          NULL,
    last_modified_by_user_id int8          NULL,
    note                     varchar(4000) NULL,
    patient_id               int8          NOT NULL,
    old_note_guid            varchar(4000) NOT NULL,
    CONSTRAINT patient_note_pkey PRIMARY KEY (id)
);

ALTER TABLE patient_note
    ADD CONSTRAINT fk_pat_note_to_modifyed_user FOREIGN KEY (last_modified_by_user_id) REFERENCES company_user (id);
ALTER TABLE patient_note
    ADD CONSTRAINT fkpat_note_to_created_user FOREIGN KEY (created_by_user_id) REFERENCES company_user (id);
ALTER TABLE patient_note
    ADD CONSTRAINT fk_pat_note_to_patient FOREIGN KEY (patient_id) REFERENCES patient_profile (id);


insert into patient_profile (first_name, last_name, old_client_guid, status_id)
values ('Andrey', 'Andreev', '17DD4E94-6ИB57-55C8-E111-CC320D1AC3FB', 200),
       ('Nikolay', 'Nikolaev', 'A699E400-8CD1-6346-D1C2-2E8332903819', 210),
       ('Natalia', 'Natalievna', '4FED329C-1FAF-0EA6-54EC-44F7443B18E6', 230),
       ('Dmitrii', 'Dmitrievich', '116FF906-BA21-3DAC-BF85-C422BEEC23A9', 230),
       ('Vasilii', 'Visilievich', '9831ABF4-7510-7E11-F391-BAB612E54FE6', 500),
       ('Jan', 'Janovich', 'B1AAB5A1-1E3A-3257-5E99-2A24564B9303', 230),
       ('Sveta', 'Svetikova', '042EF358-FAF1-A593-328A-32FC05B39993', 210),
       ('Murat', 'Nuratovich', 'F4259B4A-12AF-B674-E1B6-85B217F0972F, 51A45379-EBEE-E66D-1DDF-252DA5765443', 200);
